### ISSUE TITLE
Add Gc::as_ptr by analogy with Rc::as_ptr

### ISSUE THREAD

**Issue by anna-hope** [claytonwramsey/dumpster#10]
The standard library `Rc` has a method `as_ptr` to get the raw pointer to the value wrapped by the `Rc`, which I rely on in several places. Would you be interested in a PR that added that functionality to this crate?

**Comment by claytonwramsey** [comment]
That seems like a good idea! You're welcome to open a PR if you like; if not, I'm happy to implement it myself :).
