### ISSUE TITLE
Implement PartialEq for Gc

### ISSUE THREAD

**Issue by anna-hope** [claytonwramsey/dumpster#12]
This likely requires also implementing `Gc::ptr_eq` as an optimization. I can try doing this, if @claytonwramsey you are ok with that.

**Comment by claytonwramsey** [comment]
Sorry for being so slow about getting back to you on this!

Grad school and fellowship applications are keeping me very busy these days, so I don't have a lot of time to work on this project. If you'd like to submit a PR, I'd happily review it though. If not, I might have some free time in ~November to work on this myself.

**Comment by claytonwramsey** [comment]
I've now made an implementation of `PartialEq` and `Eq` for each kind of `Gc` in 628265f. Unfortunately, `PartialEq` does not imply reflexivity, so the pointer-based optimization is not possible without access to trait specialization. There might be some runtime trick for detecting whether a type implements `Eq` to enable this, though.
