### ISSUE TITLE
Implement Collectable for UnsafeCell

### ISSUE THREAD

**Issue by ray33ee** [claytonwramsey/dumpster#13]
The three other main cell types have implementations, and UnsafeCell can be implemented with:

```Rust
unsafe impl<T: Collectable + ?Sized> Collectable for std::cell::UnsafeCell<T> {
    #[inline]
    fn accept<V: Visitor>(&self, visitor: &mut V) -> Result<(), ()> {
        unsafe { (& mut *self.get()).accept(visitor) }
    }
}
```

I cast to a `& mut` here as it has `Visitor` implemented, but maybe `&` could be used instead?

**Comment by claytonwramsey** [comment]
I thought a little more about your proposal, and I think that there's no way to use a `Gc<UnsafeCell>` safely. The problem:

- One would only use an `UnsafeCell` in the case where they want to do something involving interior immutability.
- The garbage collector could scan the contents of the `UnsafeCell` at any time, no matter what. 

Given that, if you're using an `UnsafeCell` inside of a garbage-collected value, I think it makes more sense to require a manual implementation that enforces the necessary invariants.

If you can think of a reason as to why one might use this, I'd be happy to revive this, but for now it's probably just a major footgun.
