### ISSUE TITLE
Map collections

### ISSUE THREAD

**Issue by andrewbaxter** [claytonwramsey/dumpster#8]
I got an error about `BTreeMap` not implementing `Collectable` and I don't see an impl for `HashMap` either if I read the code right.

**Comment by claytonwramsey** [comment]
Thanks for the feedback! 

I think I understand what you mean - `BTreeMap` and `HashMap` currently don't implement `Collectable`. Is that correct? If not, clarify further. I'll look into this and add an implementation for those two in the next release.

**Comment by claytonwramsey** [comment]
0.1.2 fixes this.
